backend:
  name: github
  branch: master
  repo: matthew-nelson/pro-gatsby-2

media_folder: static/img
public_folder: /img

collections:
  - name: 'team'
    label: 'Team'
    folder: 'src/team'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Team Member', name: 'title', widget: 'string' }
      - { label: 'Slug', name: 'slug', widget: 'string' }
      - { label: 'Bio', name: 'bio', widget: 'markdown' }
      - { label: 'Page Type', name: 'page_type', widget: 'string' }
      - { label: 'Profile Picture', name: 'profile_picture', widget: 'image' }
